import { ApiProperty } from '@nestjs/swagger';

export class GetDisciplineReviewResponseDto {
  @ApiProperty({
    description: '신고 상세',
    example: [
      {
        restrictionType: 1,
        restrictionTypeName: '불건전 닉네임',
        restrictionDetail: 1,
        restrictionDetailName: '없음',
        disciplineDetail: 1,
        disciplineDetailName: '명칭 임의변경',
      },
      {
        restrictionType: 1,
        restrictionTypeName: '불건전 닉네임',
        restrictionDetail: 1,
        restrictionDetailName: '없음',
        disciplineDetail: 2,
        disciplineDetailName: '명칭 임의변경 및 3일 제한',
      },
      {
        restrictionType: 1,
        restrictionTypeName: '불건전 닉네임',
        restrictionDetail: 1,
        restrictionDetailName: '없음',
        disciplineDetail: 9,
        disciplineDetailName: '영구 제한',
      },
      {
        restrictionType: 2,
        restrictionTypeName: '시스템 버그 악용 및 불법 프로그램 사용',
        restrictionDetail: 1,
        restrictionDetailName: '없음',
        disciplineDetail: 8,
        disciplineDetailName: '15일 정지',
      },
      {
        restrictionType: 2,
        restrictionTypeName: '시스템 버그 악용 및 불법 프로그램 사용',
        restrictionDetail: 1,
        restrictionDetailName: '없음',
        disciplineDetail: 9,
        disciplineDetailName: '영구 제한',
      },
      {
        restrictionType: 2,
        restrictionTypeName: '시스템 버그 악용 및 불법 프로그램 사용',
        restrictionDetail: 1,
        restrictionDetailName: '없음',
        disciplineDetail: 10,
        disciplineDetailName: '법적 조치',
      },
      {
        restrictionType: 3,
        restrictionTypeName: '비매너 행위',
        restrictionDetail: 11,
        restrictionDetailName: '욕설 · 도배',
        disciplineDetail: 3,
        disciplineDetailName: '3일 채팅 정지',
      },
      {
        restrictionType: 3,
        restrictionTypeName: '비매너 행위',
        restrictionDetail: 11,
        restrictionDetailName: '욕설 · 도배',
        disciplineDetail: 4,
        disciplineDetailName: '7일 채팅 정지',
      },
      {
        restrictionType: 3,
        restrictionTypeName: '비매너 행위',
        restrictionDetail: 11,
        restrictionDetailName: '욕설 · 도배',
        disciplineDetail: 9,
        disciplineDetailName: '영구 제한',
      },
      {
        restrictionType: 3,
        restrictionTypeName: '비매너 행위',
        restrictionDetail: 12,
        restrictionDetailName: '선정성 · 괴롭힘  · 기타',
        disciplineDetail: 6,
        disciplineDetailName: '3일 정지',
      },
      {
        restrictionType: 3,
        restrictionTypeName: '비매너 행위',
        restrictionDetail: 12,
        restrictionDetailName: '선정성 · 괴롭힘  · 기타',
        disciplineDetail: 7,
        disciplineDetailName: '7일 정지',
      },
      {
        restrictionType: 3,
        restrictionTypeName: '비매너 행위',
        restrictionDetail: 12,
        restrictionDetailName: '선정성 · 괴롭힘  · 기타',
        disciplineDetail: 9,
        disciplineDetailName: '영구 제한',
      },
      {
        restrictionType: 4,
        restrictionTypeName: '상업성 광고 및 현금 거래',
        restrictionDetail: 1,
        restrictionDetailName: '없음',
        disciplineDetail: 8,
        disciplineDetailName: '15일 정지',
      },
      {
        restrictionType: 4,
        restrictionTypeName: '상업성 광고 및 현금 거래',
        restrictionDetail: 1,
        restrictionDetailName: '없음',
        disciplineDetail: 9,
        disciplineDetailName: '영구 제한',
      },
    ],
  })
  public readonly disciplineReviews: string;
}
