export enum RoomType {
  Arz = 'Arz',
  Busan = 'Busan',
  JumpingMatching = 'JumpingMatching',
  OXQuiz = 'OXQuiz',
  Lecture = 'Lecture',
  Meeting = 'Meeting',
  Consulting = 'Consulting',
  MyRoom = 'MyRoom',
  Conference = 'Conference',
  Game = 'Game',
  Office = 'Office',
  Store = 'Store',
  Vote = 'Vote',
  Hospital = 'Hospital',
  Festival = 'Festival',
  Unknown = 'Unknown',
}
