import { ApiProperty } from '@nestjs/swagger';

export class GetPaymentListResponseDto {
  @ApiProperty({
    description: '결제 상태 로그 리스트',
    required: true,
    example: [
      {
        orderId: 'D2XA9thQO7WeWbXTw7uA6',
        orderName: '도레미~',
        memberCode: 'XC5IDONKPTR6',
        nickName: '재벌집막내아들',
        productId: 1201,
        count: 1,
        price: 50000,
        storeType: 3,
        paymentsData: {
          mId: 'tarzmet0md1',
          lastTransactionKey: '98F5A9E6A063E51F32AB26D23BD47F4A',
          paymentKey: 'MKlA4XDvdYoEjb0gm23PjR9Dydeyk4rpGwBJn5eya1RPQkx9',
          orderId: 'D2XA9thQO7WeWbXTw7uA6',
          orderName: '도레미~',
          taxExemptionAmount: 0,
          status: 'DONE',
          requestedAt: '2023-06-12T11:37:46+09:00',
          approvedAt: '2023-06-12T11:38:03+09:00',
          useEscrow: false,
          cultureExpense: false,
          card: {
            issuerCode: '24',
            acquirerCode: '21',
            number: '53275080****909*',
            installmentPlanMonths: 0,
            isInterestFree: false,
            interestPayer: null,
            approveNo: '00000000',
            useCardPoint: false,
            cardType: '신용',
            ownerType: '개인',
            acquireStatus: 'READY',
            amount: 50000,
          },
          virtualAccount: null,
          transfer: null,
          mobilePhone: null,
          giftCertificate: null,
          cashReceipt: null,
          cashReceipts: null,
          discount: null,
          cancels: null,
          secret: 'ps_4yKeq5bgrpyKK4zoN5bx8GX0lzW6',
          type: 'NORMAL',
          easyPay: {
            provider: '토스페이',
            amount: 0,
            discountAmount: 0,
          },
          country: 'KR',
          failure: null,
          isPartialCancelable: true,
          receipt: {
            url: 'https://dashboard.tosspayments.com/receipt/redirection?transactionId=tarzm20230612113747FHPK6&ref=PX',
          },
          checkout: {
            url: 'https://api.tosspayments.com/v1/payments/MKlA4XDvdYoEjb0gm23PjR9Dydeyk4rpGwBJn5eya1RPQkx9/checkout',
          },
          currency: 'KRW',
          totalAmount: 50000,
          balanceAmount: 50000,
          suppliedAmount: 45455,
          vat: 4545,
          taxFreeAmount: 0,
          method: '간편결제',
          version: '2022-11-16',
        },
        paymentStateType: 1,
        paymentCreateAt: null,
        paymentDeleteAt: null,
        vBankCreateAt: null,
        vBankDeleteAt: null,
        createdAt: '2023-06-12T02:38:04.000Z',
        updatedAt: '2023-06-12T02:38:04.000Z',
      },
      {
        orderId: 'FggSaaGranbelNscpZFrZ',
        orderName: '도레미~',
        memberCode: 'XC5IDONKPTR6',
        nickName: '재벌집막내아들',
        productId: 1201,
        count: 1,
        price: 50000,
        storeType: 3,
        paymentsData: {
          mId: 'tarzmet0md1',
          lastTransactionKey: '5FCDF6A4574B7A8C4EA21345DD4FF6F7',
          paymentKey: 'XJxNkgDKzOEP59LybZ8BK9B5eydqG36GYo7pRe10BMQwla2v',
          orderId: 'FggSaaGranbelNscpZFrZ',
          orderName: '도레미~',
          taxExemptionAmount: 0,
          status: 'DONE',
          requestedAt: '2023-06-07T18:06:18+09:00',
          approvedAt: '2023-06-07T18:06:37+09:00',
          useEscrow: false,
          cultureExpense: false,
          card: {
            issuerCode: '24',
            acquirerCode: '21',
            number: '53275080****909*',
            installmentPlanMonths: 0,
            isInterestFree: false,
            interestPayer: null,
            approveNo: '00000000',
            useCardPoint: false,
            cardType: '신용',
            ownerType: '개인',
            acquireStatus: 'READY',
            amount: 50000,
          },
          virtualAccount: null,
          transfer: null,
          mobilePhone: null,
          giftCertificate: null,
          cashReceipt: null,
          cashReceipts: null,
          discount: null,
          cancels: null,
          secret: 'ps_d46qopOB897gpbGz7AjKVZmM75y0',
          type: 'NORMAL',
          easyPay: {
            provider: '토스페이',
            amount: 0,
            discountAmount: 0,
          },
          country: 'KR',
          failure: null,
          isPartialCancelable: true,
          receipt: {
            url: 'https://dashboard.tosspayments.com/receipt/redirection?transactionId=tarzm20230607180619BIAy8&ref=PX',
          },
          checkout: {
            url: 'https://api.tosspayments.com/v1/payments/XJxNkgDKzOEP59LybZ8BK9B5eydqG36GYo7pRe10BMQwla2v/checkout',
          },
          currency: 'KRW',
          totalAmount: 50000,
          balanceAmount: 50000,
          suppliedAmount: 45455,
          vat: 4545,
          taxFreeAmount: 0,
          method: '간편결제',
          version: '2022-11-16',
        },
        paymentStateType: 1,
        paymentCreateAt: null,
        paymentDeleteAt: null,
        vBankCreateAt: null,
        vBankDeleteAt: null,
        createdAt: '2023-06-07T09:06:45.000Z',
        updatedAt: '2023-06-12T06:58:14.000Z',
      },
      {
        orderId: 'iKwkDnppuGntJyszG4ECp',
        orderName: '도레미~',
        memberCode: 'XC5IDONKPTR6',
        nickName: '재벌집막내아들',
        productId: 1201,
        count: 1,
        price: 50000,
        storeType: 3,
        paymentsData: {
          mId: 'tarzmet0md1',
          lastTransactionKey: '93DB1D59FE10E01ADAAB8D6BEB2BDE56',
          paymentKey: 'lqNRYD097kZLKGPx4M3MpBEz2Km27w8BaWypv1o6bemnOJz2',
          orderId: 'iKwkDnppuGntJyszG4ECp',
          orderName: '도레미~',
          taxExemptionAmount: 0,
          status: 'DONE',
          requestedAt: '2023-06-07T21:11:36+09:00',
          approvedAt: '2023-06-07T21:12:12+09:00',
          useEscrow: false,
          cultureExpense: false,
          card: {
            issuerCode: '51',
            acquirerCode: '51',
            number: '37798973****88*',
            installmentPlanMonths: 0,
            isInterestFree: false,
            interestPayer: null,
            approveNo: '00000000',
            useCardPoint: false,
            cardType: '신용',
            ownerType: '개인',
            acquireStatus: 'READY',
            amount: 50000,
          },
          virtualAccount: null,
          transfer: null,
          mobilePhone: null,
          giftCertificate: null,
          cashReceipt: null,
          cashReceipts: null,
          discount: null,
          cancels: null,
          secret: 'ps_vZnjEJeQVxBGXg66ZgZ8PmOoBN0k',
          type: 'NORMAL',
          easyPay: null,
          country: 'KR',
          failure: null,
          isPartialCancelable: true,
          receipt: {
            url: 'https://dashboard.tosspayments.com/receipt/redirection?transactionId=tarzm20230607211212d1dB7&ref=PX',
          },
          checkout: {
            url: 'https://api.tosspayments.com/v1/payments/lqNRYD097kZLKGPx4M3MpBEz2Km27w8BaWypv1o6bemnOJz2/checkout',
          },
          currency: 'KRW',
          totalAmount: 50000,
          balanceAmount: 50000,
          suppliedAmount: 45455,
          vat: 4545,
          taxFreeAmount: 0,
          method: '카드',
          version: '2022-11-16',
        },
        paymentStateType: 1,
        paymentCreateAt: null,
        paymentDeleteAt: null,
        vBankCreateAt: null,
        vBankDeleteAt: null,
        createdAt: '2023-06-07T12:12:41.000Z',
        updatedAt: '2023-06-07T12:12:41.000Z',
      },
      {
        orderId: 'OEm2sqfo88cqooo1gH32R',
        orderName: '도레미~',
        memberCode: 'XC5IDONKPTR6',
        nickName: '재벌집막내아들',
        productId: 1201,
        count: 1,
        price: 50000,
        storeType: 3,
        paymentsData: {
          mId: 'tarzmet0md1',
          lastTransactionKey: 'D8E171B13377FD7984E7ED7250FEFE92',
          paymentKey: 'xMljweGQBN5OWRapdA8dj2pPKWdWbXVo1zEqZKLPbmD70vk4',
          orderId: 'OEm2sqfo88cqooo1gH32R',
          orderName: '도레미~',
          taxExemptionAmount: 0,
          status: 'DONE',
          requestedAt: '2023-06-12T11:39:01+09:00',
          approvedAt: '2023-06-12T11:39:15+09:00',
          useEscrow: false,
          cultureExpense: false,
          card: {
            issuerCode: '24',
            acquirerCode: '21',
            number: '53275080****909*',
            installmentPlanMonths: 0,
            isInterestFree: false,
            interestPayer: null,
            approveNo: '00000000',
            useCardPoint: false,
            cardType: '신용',
            ownerType: '개인',
            acquireStatus: 'READY',
            amount: 50000,
          },
          virtualAccount: null,
          transfer: null,
          mobilePhone: null,
          giftCertificate: null,
          cashReceipt: null,
          cashReceipts: null,
          discount: null,
          cancels: null,
          secret: 'ps_QbgMGZzorzmaqx7G5XEKVl5E1em4',
          type: 'NORMAL',
          easyPay: {
            provider: '토스페이',
            amount: 0,
            discountAmount: 0,
          },
          country: 'KR',
          failure: null,
          isPartialCancelable: true,
          receipt: {
            url: 'https://dashboard.tosspayments.com/receipt/redirection?transactionId=tarzm20230612113902FHPN9&ref=PX',
          },
          checkout: {
            url: 'https://api.tosspayments.com/v1/payments/xMljweGQBN5OWRapdA8dj2pPKWdWbXVo1zEqZKLPbmD70vk4/checkout',
          },
          currency: 'KRW',
          totalAmount: 50000,
          balanceAmount: 50000,
          suppliedAmount: 45455,
          vat: 4545,
          taxFreeAmount: 0,
          method: '간편결제',
          version: '2022-11-16',
        },
        paymentStateType: 1,
        paymentCreateAt: null,
        paymentDeleteAt: null,
        vBankCreateAt: null,
        vBankDeleteAt: null,
        createdAt: '2023-06-12T02:39:15.000Z',
        updatedAt: '2023-06-12T02:39:15.000Z',
      },
      {
        orderId: 'TqGxQHMAKtsLpI7Ux4ncj',
        orderName: '도레미~',
        memberCode: 'XC5IDONKPTR6',
        nickName: '재벌집막내아들',
        productId: 1201,
        count: 1,
        price: 50000,
        storeType: 3,
        paymentsData: {
          mId: 'tarzmet0md1',
          lastTransactionKey: '7FF438601DC5CA6E1524A4F2B70DFBDC',
          paymentKey: 'dJv2eBNjG0Poxy1XQL8R9Qg9PO679Xr7nO5Wmlg96RKwZz4Y',
          orderId: 'TqGxQHMAKtsLpI7Ux4ncj',
          orderName: '도레미~',
          taxExemptionAmount: 0,
          status: 'DONE',
          requestedAt: '2023-06-12T11:36:39+09:00',
          approvedAt: '2023-06-12T11:36:54+09:00',
          useEscrow: false,
          cultureExpense: false,
          card: {
            issuerCode: '24',
            acquirerCode: '21',
            number: '53275080****909*',
            installmentPlanMonths: 0,
            isInterestFree: false,
            interestPayer: null,
            approveNo: '00000000',
            useCardPoint: false,
            cardType: '신용',
            ownerType: '개인',
            acquireStatus: 'READY',
            amount: 50000,
          },
          virtualAccount: null,
          transfer: null,
          mobilePhone: null,
          giftCertificate: null,
          cashReceipt: null,
          cashReceipts: null,
          discount: null,
          cancels: null,
          secret: 'ps_eqRGgYO1r5OENekA4Dvn3QnN2Eya',
          type: 'NORMAL',
          easyPay: {
            provider: '토스페이',
            amount: 0,
            discountAmount: 0,
          },
          country: 'KR',
          failure: null,
          isPartialCancelable: true,
          receipt: {
            url: 'https://dashboard.tosspayments.com/receipt/redirection?transactionId=tarzm20230612113639EOK48&ref=PX',
          },
          checkout: {
            url: 'https://api.tosspayments.com/v1/payments/dJv2eBNjG0Poxy1XQL8R9Qg9PO679Xr7nO5Wmlg96RKwZz4Y/checkout',
          },
          currency: 'KRW',
          totalAmount: 50000,
          balanceAmount: 50000,
          suppliedAmount: 45455,
          vat: 4545,
          taxFreeAmount: 0,
          method: '간편결제',
          version: '2022-11-16',
        },
        paymentStateType: 1,
        paymentCreateAt: null,
        paymentDeleteAt: null,
        vBankCreateAt: null,
        vBankDeleteAt: null,
        createdAt: '2023-06-12T02:36:55.000Z',
        updatedAt: '2023-06-12T02:36:55.000Z',
      },
      {
        orderId: 'y2boapbBq7zRiBumqCPUK',
        orderName: '도레미~',
        memberCode: 'XC5IDONKPTR6',
        nickName: '재벌집막내아들',
        productId: 1201,
        count: 1,
        price: 50000,
        storeType: 3,
        paymentsData: {
          mId: 'tarzmet0md1',
          lastTransactionKey: '3F857B14EF34D46AAB671FA888A70B6A',
          paymentKey: '01OAv2P6yqLlDJaYngroodRZ6QMLwvrezGdRpXxKN7BQMEk4',
          orderId: 'y2boapbBq7zRiBumqCPUK',
          orderName: '도레미~',
          taxExemptionAmount: 0,
          status: 'DONE',
          requestedAt: '2023-06-12T11:30:52+09:00',
          approvedAt: '2023-06-12T11:31:06+09:00',
          useEscrow: false,
          cultureExpense: false,
          card: {
            issuerCode: '24',
            acquirerCode: '21',
            number: '53275080****909*',
            installmentPlanMonths: 0,
            isInterestFree: false,
            interestPayer: null,
            approveNo: '00000000',
            useCardPoint: false,
            cardType: '신용',
            ownerType: '개인',
            acquireStatus: 'READY',
            amount: 50000,
          },
          virtualAccount: null,
          transfer: null,
          mobilePhone: null,
          giftCertificate: null,
          cashReceipt: null,
          cashReceipts: null,
          discount: null,
          cancels: null,
          secret: 'ps_XZYkKL4MrjeNb1MKXGeLV0zJwlEW',
          type: 'NORMAL',
          easyPay: {
            provider: '토스페이',
            amount: 0,
            discountAmount: 0,
          },
          country: 'KR',
          failure: null,
          isPartialCancelable: true,
          receipt: {
            url: 'https://dashboard.tosspayments.com/receipt/redirection?transactionId=tarzm20230612113053FHPm2&ref=PX',
          },
          checkout: {
            url: 'https://api.tosspayments.com/v1/payments/01OAv2P6yqLlDJaYngroodRZ6QMLwvrezGdRpXxKN7BQMEk4/checkout',
          },
          currency: 'KRW',
          totalAmount: 50000,
          balanceAmount: 50000,
          suppliedAmount: 45455,
          vat: 4545,
          taxFreeAmount: 0,
          method: '간편결제',
          version: '2022-11-16',
        },
        paymentStateType: 1,
        paymentCreateAt: null,
        paymentDeleteAt: null,
        vBankCreateAt: null,
        vBankDeleteAt: null,
        createdAt: '2023-06-12T02:31:06.000Z',
        updatedAt: '2023-06-12T02:31:06.000Z',
      },
    ],
  })
  public readonly paymentList: string;
}
